// Augments the global CloudflareEnv interface used by @opennextjs/cloudflare
// with the bindings defined in worker-configuration.d.ts (generated by `wrangler types`).
interface CloudflareEnv {
  R2: R2Bucket;
  NEXT_PUBLIC_MAPBOX_TOKEN: string;
  NEXT_PUBLIC_BASE_URL: string;
  GITHUB_TOKEN_USER: string;
  GITHUB_USER_EMAIL: string;
  GITHUB_BRANCH_NAME: string;
  API_UBICATE_SECRET: string;
  NEXT_PUBLIC_IS_SELF_HOST: string;
  OUTBOUND_PROXY: string;
}
