const GITHUB_TOKEN_USER = process.env.GITHUB_TOKEN_USER;
const GITHUB_BRANCH_NAME = process.env.GITHUB_BRANCH_NAME;
const GITHUB_USER_EMAIL = process.env.GITHUB_USER_EMAIL;

export { GITHUB_TOKEN_USER, GITHUB_BRANCH_NAME, GITHUB_USER_EMAIL };
