import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import "mapbox-gl/dist/mapbox-gl.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex w-screen h-screen flex-col justify-between ">
          <nav className="w-screen text-black bg-blue-200 h-10 flex flex-row">
            <Link href="" className="my-1 mx-2">
              Home
            </Link>
            <Link href="/map" className="my-1 mx-2">
              Map
            </Link>
            <Link href="/form-geo" className="my-1 mx-2">
              Form
            </Link>
          </nav>
          {children}
        </main>
      </body>
    </html>
  );
}
