import { StyleSpecification } from "maplibre-gl";

export const darkThemeMap: StyleSpecification = {
  version: 8,
  name: "Ubicate-Style-MapLibre",
  glyphs: "/api/font/{fontstack}/{range}",
  sources: {
    localtiles: {
      type: "vector",
      tiles: ["/api/{z}/{x}/{y}"],
      minzoom: 0,
      maxzoom: 14,
    },
  },
  layers: [
    {
      id: "background",
      type: "background",
      paint: {
        "background-color": "#374d64",
      },
    },
    {
      id: "landuse",
      type: "fill",
      source: "localtiles",
      "source-layer": "landuse",
      minzoom: 3,
      paint: {
        "fill-color": [
          "case",
          ["==", ["get", "class"], "park"],
          "#005d5b",
          ["==", ["get", "class"], "recreation_ground"],
          "#005d5b",
          ["==", ["get", "class"], "leisure"],
          "#005d5b",
          ["==", ["get", "class"], "garden"],
          "#005d5b",
          ["==", ["get", "class"], "cemetery"],
          "#0d6a68",
          ["==", ["get", "class"], "wood"],
          "#075251",
          ["==", ["get", "class"], "grass"],
          "#005d5b",
          ["==", ["get", "class"], "agriculture"],
          "#005d5b",
          ["==", ["get", "class"], "meadow"],
          "#005d5b",
          ["==", ["get", "class"], "forest"],
          "#075251",
          ["==", ["get", "class"], "residential"],
          "#262c33",
          ["==", ["get", "class"], "commercial"],
          "#374d64",
          ["==", ["get", "class"], "industrial"],
          "#374d64",
          ["==", ["get", "class"], "hospital"],
          "#374d64",
          ["==", ["get", "class"], "college"],
          "#3d4c5c",
          ["==", ["get", "class"], "military"],
          "#374d64",
          ["==", ["get", "class"], "university"],
          "#3d4c5c",
          ["==", ["get", "class"], "school"],
          "#3d4c5c",
          ["==", ["get", "class"], "airport"],
          "#002148",
          "#273d41",
        ],
        "fill-opacity": [
          "interpolate",
          ["linear"],
          ["zoom"],
          8,
          ["case", ["==", ["get", "class"], "residential"], 0.8, 0.2],
          10,
          ["case", ["==", ["get", "class"], "residential"], 0, 1],
        ],
      },
    },
    {
      id: "landcover",
      type: "fill",
      source: "localtiles",
      "source-layer": "landcover",
      filter: ["in", "class", "wood", "grass", "scrub", "crop", "snow"],
      paint: {
        "fill-color": [
          "case",
          ["==", ["get", "class"], "wood"],
          "#075251",
          ["==", ["get", "class"], "snow"],
          "#6578b0",
          ["==", ["get", "class"], "grass"],
          "#273d41",
          ["==", ["get", "class"], "scrub"],
          "#273d41",
          ["==", ["get", "class"], "crop"],
          "#273d41",
          "#273d41",
        ],
        "fill-opacity": ["interpolate", ["linear"], ["zoom"], 9, 0.4, 10, 0.4, 11, 0.4, 12, 0.8],
      },
    },
    {
      id: "water",
      type: "fill",
      source: "localtiles",
      "source-layer": "water",
      paint: {
        "fill-color": "#104e7c",
      },
    },
    {
      id: "landuse-pitches",
      type: "fill",
      source: "localtiles",
      "source-layer": "landuse",
      minzoom: 3,
      filter: ["==", ["get", "class"], "pitch"],
      paint: {
        "fill-color": "#004d5b",
        "fill-opacity": 1.0,
      },
    },
    {
      id: "waterway",
      type: "line",
      source: "localtiles",
      "source-layer": "waterway",
      minzoom: 8,
      layout: {
        "line-cap": "round",
        "line-join": "round",
      },
      paint: {
        "line-color": "#1c347a",
        "line-width": [
          "interpolate",
          ["exponential", 1.3],
          ["zoom"],
          9,
          ["case", ["in", ["get", "class"], ["literal", ["river", "canal"]]], 0.1, 0],
          20,
          ["case", ["in", ["get", "class"], ["literal", ["river", "canal"]]], 8, 3],
        ],
        "line-opacity": ["interpolate", ["linear"], ["zoom"], 8, 0, 8.5, 1],
      },
    },
    {
      id: "building",
      type: "fill",
      source: "localtiles",
      "source-layer": "building",
      minzoom: 10,
      paint: {
        "fill-color": "#242f3a",
        "fill-opacity": ["interpolate", ["linear"], ["zoom"], 10, 0.3, 12, 0.5, 14, 0.7, 16, 1],
        "fill-outline-color": "rgba(15, 19, 22, 0.8)",
      },
    },
    {
      id: "transportation-path-stroke",
      type: "line",
      source: "localtiles",
      "source-layer": "transportation",
      minzoom: 12,
      filter: ["==", ["get", "class"], "path"],
      layout: {
        "line-cap": "round",
        "line-join": "round",
      },
      paint: {
        "line-color": "#4a5a70",
        "line-width": ["interpolate", ["exponential", 1.5], ["zoom"], 13, 1.5, 14, 2, 15, 2, 18, 6],
        "line-opacity": 0.8,
      },
    },
    {
      id: "transportation-path",
      type: "line",
      source: "localtiles",
      "source-layer": "transportation",
      minzoom: 12,
      filter: ["==", ["get", "class"], "path"],
      layout: {
        "line-cap": "round",
        "line-join": "round",
      },
      paint: {
        "line-color": "#616f84",
        "line-width": ["interpolate", ["exponential", 1.5], ["zoom"], 13, 0.5, 14, 1, 15, 1, 18, 4],
        "line-dasharray": [10, 0],
      },
    },
    {
      id: "transportation-minor-stroke",
      type: "line",
      source: "localtiles",
      "source-layer": "transportation",
      minzoom: 12,
      filter: ["in", ["get", "class"], ["literal", ["minor", "service", "track"]]],
      layout: {
        "line-cap": "round",
        "line-join": "round",
      },
      paint: {
        "line-color": "#4a5566",
        "line-width": ["interpolate", ["exponential", 1.5], ["zoom"], 13, 1.5, 18, 14, 22, 122],
        "line-opacity": 0.8,
      },
    },
    {
      id: "transportation-minor",
      type: "line",
      source: "localtiles",
      "source-layer": "transportation",
      minzoom: 12,
      filter: ["in", ["get", "class"], ["literal", ["minor", "service", "track"]]],
      layout: {
        "line-cap": "round",
        "line-join": "round",
      },
      paint: {
        "line-color": "#5b687b",
        "line-width": ["interpolate", ["exponential", 1.5], ["zoom"], 13, 0.5, 18, 12, 22, 120],
      },
    },
    {
      id: "transportation-secondary-stroke",
      type: "line",
      source: "localtiles",
      "source-layer": "transportation",
      minzoom: 8,
      filter: ["==", ["get", "class"], "secondary"],
      layout: {
        "line-cap": "round",
        "line-join": "round",
      },
      paint: {
        "line-color": "#4a5a70",
        "line-width": ["interpolate", ["exponential", 1.5], ["zoom"], 8, 0.5, 13, 4.5, 18, 28, 22, 262],
        "line-opacity": 0.8,
      },
    },
    {
      id: "transportation-secondary",
      type: "line",
      source: "localtiles",
      "source-layer": "transportation",
      minzoom: 8,
      filter: ["==", ["get", "class"], "secondary"],
      layout: {
        "line-cap": "round",
        "line-join": "round",
      },
      paint: {
        "line-color": "#616f84",
        "line-width": ["interpolate", ["exponential", 1.5], ["zoom"], 8, 0.1, 13, 2.5, 18, 26, 22, 260],
      },
    },
    {
      id: "transportation-primary-stroke",
      type: "line",
      source: "localtiles",
      "source-layer": "transportation",
      minzoom: 6,
      filter: ["==", ["get", "class"], "primary"],
      layout: {
        "line-cap": "round",
        "line-join": "round",
      },
      paint: {
        "line-color": "#4a5a70",
        "line-width": ["interpolate", ["exponential", 1.5], ["zoom"], 6, 1.5, 13, 6, 18, 34, 22, 322],
        "line-opacity": 0.8,
      },
    },
    {
      id: "transportation-primary",
      type: "line",
      source: "localtiles",
      "source-layer": "transportation",
      minzoom: 6,
      filter: ["==", ["get", "class"], "primary"],
      layout: {
        "line-cap": "round",
        "line-join": "round",
      },
      paint: {
        "line-color": "#616f84",
        "line-width": ["interpolate", ["exponential", 1.5], ["zoom"], 6, 0.75, 13, 4, 18, 32, 22, 320],
      },
    },
    {
      id: "transportation-trunk-stroke",
      type: "line",
      source: "localtiles",
      "source-layer": "transportation",
      minzoom: 5,
      filter: ["==", ["get", "class"], "trunk"],
      layout: {
        "line-cap": "round",
        "line-join": "round",
      },
      paint: {
        "line-color": "#4a5a70",
        "line-width": ["interpolate", ["exponential", 1.5], ["zoom"], 5, 1.5, 13, 6, 18, 34, 22, 322],
        "line-opacity": 0.8,
      },
    },
    {
      id: "transportation-trunk",
      type: "line",
      source: "localtiles",
      "source-layer": "transportation",
      minzoom: 5,
      filter: ["==", ["get", "class"], "trunk"],
      layout: {
        "line-cap": "round",
        "line-join": "round",
      },
      paint: {
        "line-color": "#616f84",
        "line-width": ["interpolate", ["exponential", 1.5], ["zoom"], 5, 0.75, 13, 4, 18, 32, 22, 320],
      },
    },
    {
      id: "transportation-motorway-stroke",
      type: "line",
      source: "localtiles",
      "source-layer": "transportation",
      minzoom: 5,
      filter: ["==", ["get", "class"], "motorway"],
      layout: {
        "line-cap": "round",
        "line-join": "round",
      },
      paint: {
        "line-color": "#4a5a70",
        "line-width": ["interpolate", ["exponential", 1.5], ["zoom"], 5, 1.5, 13, 6, 18, 34, 22, 322],
        "line-opacity": 0.8,
      },
    },
    {
      id: "transportation-motorway",
      type: "line",
      source: "localtiles",
      "source-layer": "transportation",
      minzoom: 5,
      filter: ["==", ["get", "class"], "motorway"],
      layout: {
        "line-cap": "round",
        "line-join": "round",
      },
      paint: {
        "line-color": "#616f84",
        "line-width": ["interpolate", ["exponential", 1.5], ["zoom"], 5, 0.75, 13, 4, 18, 32, 22, 320],
      },
    },
    {
      id: "transportation-rail",
      type: "line",
      source: "localtiles",
      "source-layer": "transportation",
      minzoom: 13,
      filter: ["in", ["get", "class"], "rail"],
      paint: {
        "line-color": ["interpolate", ["linear"], ["zoom"], 13, "#1d253c", 16, "#58626c"],
        "line-width": ["interpolate", ["exponential", 1.5], ["zoom"], 14, 0.5, 20, 1],
      },
    },
    {
      id: "transportation_name",
      type: "symbol",
      source: "localtiles",
      "source-layer": "transportation_name",
      minzoom: 14,
      filter: ["in", ["get", "class"], ["literal", ["primary", "secondary", "trunk", "motorway"]]],
      layout: {
        "text-field": ["case", ["has", "name:latin"], ["get", "name:latin"], ["has", "name"], ["get", "name"], ""],
        "text-font": ["Roboto Slab Regular", "Arial Unicode MS Regular"],
        "text-size": [
          "interpolate",
          ["linear"],
          ["zoom"],
          10,
          [
            "case",
            ["in", ["get", "class"], ["literal", ["motorway", "trunk", "primary", "secondary", "tertiary"]]],
            10,
            9,
          ],
          18,
          [
            "case",
            ["in", ["get", "class"], ["literal", ["motorway", "trunk", "primary", "secondary", "tertiary"]]],
            16,
            14,
          ],
        ],
        "text-max-angle": 30,
        "symbol-placement": "line",
        "text-padding": 5,
        "text-rotation-alignment": "map",
        "text-pitch-alignment": "viewport",
        "text-letter-spacing": 0.01,
      },
      paint: {
        "text-color": "#b7c8e6",
        "text-halo-color": "#212e3d",
        "text-halo-width": 1,
      },
    },
    {
      id: "poi",
      type: "symbol",
      source: "localtiles",
      "source-layer": "poi",
      minzoom: 12,
      filter: [
        "all",
        ["has", "name:latin"],
        [
          "any",
          ["<=", ["get", "rank"], 1],
          ["==", ["get", "class"], "university"],
          ["==", ["get", "class"], "college"],
        ],
        ["!=", ["get", "class"], "bus_stop"],
        ["!=", ["get", "class"], "railway"],
        ["!=", ["get", "class"], "pharmacy"],
        ["!=", ["get", "class"], "doctor"],
      ],
      layout: {
        "text-field": ["coalesce", ["get", "name:latin"], ["get", "name"]],
        "text-font": [
          "case",
          ["in", ["get", "class"], ["literal", ["university", "college"]]],
          ["literal", ["Roboto Slab SemiBold", "Arial Unicode MS Bold"]],
          ["literal", ["Roboto Slab Medium", "Arial Unicode MS Regular"]],
        ],
        "text-size": ["case", ["in", ["get", "class"], ["literal", ["university", "college"]]], 14, 13],
        "symbol-sort-key": ["get", "rank"],
        "text-offset": [0, 0],
        "text-anchor": "center",
      },
      paint: {
        "text-halo-color": "#1f2c39",
        "text-halo-width": 0.5,
        "text-halo-blur": 0.5,
        "text-color": ["case", ["==", ["get", "class"], "park"], "#b5c4a9", "#9fb4d3"],
      },
    },
  ],
};
